Repository LiveSplit/LiveSplit, pull requests merged in 2022-11, with the labels that each got.

#2280 Add support for ScriptType element in AutoSplitters XML
  LiveSplit/LiveSplit.Core/Model/AutoSplitterFactory.cs
  LiveSplit/LiveSplit.Tests/AutoSplitterTests/AutoSplitterXML.cs
Labels: Enhancement

#2281 Improve accuracy of how times are stored
  LiveSplit/LiveSplit.Core/Model/Comparisons/AverageSegmentsComparisonGenerator.cs
  LiveSplit/LiveSplit.Core/Model/NTP.cs
  LiveSplit/LiveSplit.Core/Model/RunFactories/StandardFormatsRunFactory.cs
  LiveSplit/LiveSplit.Core/Model/TimeSpanParser.cs
  LiveSplit/LiveSplit.Core/Model/TimeStamp.cs
Labels: Bug, Enhancement, User Feature

#2287 Don't parse TimeSpans as floats
  LiveSplit/LiveSplit.Core/Model/TimeSpanParser.cs
  LiveSplit/LiveSplit.Tests/LiveSplit.Tests.csproj
  LiveSplit/LiveSplit.Tests/TimeParseTests/TimeSpanParserTests.cs
Labels: Bug
