Repository LiveSplit/LiveSplit, pull requests merged in 2024-04, with the labels that each got.

#2429 Convert `IrcDotNet` to NuGet package
  LiveSplit/Libs/IRC.Net 0.3/IrcDotNet.Common.dll
  LiveSplit/Libs/IRC.Net 0.3/IrcDotNet.Common.xml
  LiveSplit/Libs/IRC.Net 0.3/IrcDotNet.dll
  LiveSplit/Libs/IRC.Net 0.3/IrcDotNet.xml
  LiveSplit/LiveSplit.Core/LiveSplit.Core.csproj
  LiveSplit/LiveSplit.Core/Web/SRL/SpeedRunsLiveIRC.cs
  LiveSplit/LiveSplit.Core/packages.config
Labels: Enhancement

#2455 Skip incompatible image formats
  src/LiveSplit.Core/Model/RunFactories/StandardFormatsRunFactory.cs
Labels: Bug, Enhancement

#2456 Server: added command addloadingtimes
  README.md
  src/LiveSplit.Core/Server/CommandServer.cs
Labels: Enhancement

#2483 Remove extra asr_capi.dll files
  src/LiveSplit/LiveSplit.csproj
Labels: bug

#2485 Add share to X (Twitter) with web intents.
  README.md
  src/LiveSplit.Core/Web/Share/ShareSettings.Designer.cs
  src/LiveSplit.Core/Web/Share/ShareSettings.settings
  src/LiveSplit.Core/Web/Share/Twitter.cs
  src/LiveSplit.Core/app.config
  src/LiveSplit.View/View/ShareRunDialog.cs
Labels: enhancement
